## Librerias y directorios

### Importacion de librerias

In [1]:
# Bibliotecas para Manipulación de Datos y Análisis
import pandas as pd 
import numpy as np 

# Bibliotecas para Manejo de Archivos
import requests 
import zipfile  
import os  

# Visualización de Datos Perdidos
import missingno as msno

# Recolección y comprensión de los Datos

In [59]:
path_csv_update = '../data/bronze/shopping_behavior_updated.csv'
df = pd.read_csv(path_csv_update)

### Descubriendo los datos

### Descripcion y estadisticas basicas

Luego se analizaran visaulmente en la etapa de EDA

In [60]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3900.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.749949,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716223,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.700000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

### Extraccion de metadatos

In [61]:
df.dtypes

Customer ID                 int64
Age                         int64
Gender                     object
Item Purchased             object
Category                   object
Purchase Amount (USD)       int64
Location                   object
Size                       object
Color                      object
Season                     object
Review Rating             float64
Subscription Status        object
Shipping Type              object
Discount Applied           object
Promo Code Used            object
Previous Purchases          int64
Payment Method             object
Frequency of Purchases     object
dtype: object

In [62]:
categorical_variables = df.select_dtypes(exclude=['number']).columns

In [70]:
unique_categories = pd.Series({})

for column in df[categorical_variables]:
    unique_categories[column] = df[column].unique()

In [74]:
count_unique_values = unique_categories.value_counts()

In [68]:
print(count_unique_values)

[Male, Female]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                1
[Blouse, Sweater, Jeans, Sandals, Sneakers, Shirt, Shorts, Coat, Handbag, Shoes, Dress, Skirt, Sunglasses, Pants, Jacket, Hoodie, Jewelry, T-shirt, Scarf, Hat, Socks, Backpack, Belt, Boots, Gloves]                                                                                                                                                                                                                                                                                                                                         1
[Clothing, Footwear, Outerwear, Accessories]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  1
[Kentucky, Maine, Massachusetts, Rhode Island, Oregon, Wyoming, Montana, Louisiana, West Virginia, Missouri, Arkansas, Hawaii, Delaware, New Hampshire, New York, Alabama, Mississippi, North Carolina, California, Oklahoma, Florida, Texas, Nevada, Kansas, Colorado, North Dakota, Illinois, Indiana, Arizona, Alaska, Tennessee, Ohio, New Jersey, Maryland, Vermont, New Mexico, South Carolina, Idaho, Pennsylvania, Connecticut, Utah, Virginia, Georgia, Nebraska, Iowa, South Dakota, Minnesota, Washington, Wisconsin, Michigan]    1
[L, S, M, XL]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 1
[Gray, Maroon, Turquoise, White, Charcoal, Silver, Pink, Purple, Olive, Gold, Violet, Teal, Lavender, Black, Green, Peach, Red, Cyan, Brown, Beige, Orange, Indigo, Yellow, Magenta, Blue]                                                                                                                                                                                                                                                                                                                                                    1
[Winter, Spring, Summer, Fall]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                1
[Yes, No]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     1
[Express, Free Shipping, Next Day Air, Standard, 2-Day Shipping, Store Pickup]                                                                                                                                                                                                                                                                                                                                                                                                                                                                1
[Yes, No]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     1
[Yes, No]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     1
[Venmo, Cash, Credit Card, PayPal, Bank Transfer, Debit Card]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 1
[Fortnightly, Weekly, Annually, Quarterly, Bi-Weekly, Monthly, Every 3 Months]                                                                                                                                                                                                                                                                                                                                                                                                                                                                1
Name: count, dtype: int64

### Diccionario de datos

| Columna                   | Tipo de dato | Descripción                                      | Variables únicas                                                      |
|----------------------------|--------------|--------------------------------------------------|-----------------------------------------------------------------------|
| **Customer ID**            | int64        | Identificador único para cada cliente            | -                                                                     |
| **Age**                    | int64        | Edad del cliente                                 | -                                                                     |
| **Gender**                 | category     | Género del cliente                               | Male, Female                                                          |
| **Item Purchased**         | category     | Producto adquirido                               | Blouse, Sweater, Jeans, Sandals, Sneakers, Shirt, Shorts, Coat, Handbag, Shoes, Dress, Skirt, Sunglasses, Pants, Jacket, Hoodie, Jewelry, T-shirt, Scarf, Hat, Socks, Backpack, Belt, Boots, Gloves |
| **Category**               | category     | Categoría del producto                           | Clothing, Footwear, Outerwear, Accessories                            |
| **Purchase Amount (USD)**  | int64        | Monto total de la compra en dólares              | -                                                                     |
| **Location**               | category     | Ubicación geográfica del cliente                 | Kentucky, Maine, Massachusetts, Rhode Island, Oregon, Wyoming, Montana, Louisiana, West Virginia, Missouri, Arkansas, Hawaii, Delaware, New Hampshire, New York, Alabama, Mississippi, North Carolina, California, Oklahoma, Florida, Texas, Nevada, Kansas, Colorado, North Dakota, Illinois, Indiana, Arizona, Alaska, Tennessee, Ohio, New Jersey, Maryland, Vermont, New Mexico, South Carolina, Idaho, Pennsylvania, Connecticut, Utah, Virginia, Georgia, Nebraska, Iowa, South Dakota, Minnesota, Washington, Wisconsin, Michigan |
| **Size**                   | category     | Talla del producto                               | L, S, M, XL                                                           |
| **Color**                  | category     | Color del producto                               | Gray, Maroon, Turquoise, White, Charcoal, Silver, Pink, Purple, Olive, Gold, Violet, Teal, Lavender, Black, Green, Peach, Red, Cyan, Brown, Beige, Orange, Indigo, Yellow, Magenta, Blue |
| **Season**                 | category     | Temporada de la compra                           | Winter, Spring, Summer, Fall                                                 |
| **Review Rating**          | float64      | Calificación del producto por parte del cliente  | -                                                                            |
| **Subscription Status**    | category     | Estado de la suscripción del cliente             | Yes, No                                                                      |
| **Shipping Type**          | category     | Tipo de envío seleccionado                       | Express, Free Shipping, Next Day Air, Standard, 2-Day Shipping, Store Pickup |
| **Discount Applied**       | category     | Indica si se aplicó un descuento                 | Yes, No                                                                      |
| **Promo Code Used**        | category     | Indica si se utilizó un código promocional       | Yes, No                                                                      |
| **Previous Purchases**     | int64        | Número de compras anteriores del cliente         | -                                                                            |
| **Payment Method**         | category     | Método de pago utilizado                         | Venmo, Cash, Credit Card, PayPal, Bank Transfer, Debit Card                  |
| **Frequency of Purchases** | category     | Frecuencia con la que el cliente realiza compras | Fortnightly, Weekly, Annually, Quarterly, Bi-Weekly, Monthly, Every 3 Months |

### Guardado de datasets

In [76]:
# guardo los dataframes con archivo .csv dentro de la carpeta "bronze"
path_csv = '../data/bronze/clients_behavior.csv'
df.to_csv(path_csv_from_library, index=False)